<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Praveens-MBP.Home" failures="1" tests="3" name="Test" time="10.091" errors="0" timestamp="2023-12-13T16:54:21 GMT">
  <testcase classname="SwagLabs.Tests.ErrorvalidationTest" name="cartPageErrorValidation" time="3.831"/>
  <testcase classname="SwagLabs.Tests.ErrorvalidationTest" name="confirmationMessageValidation" time="3.612"/>
  <testcase classname="SwagLabs.Tests.ErrorvalidationTest" name="loginErrorvalidation" time="2.356">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not_ match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not_ match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at SwagLabs.Tests.ErrorvalidationTest.loginErrorvalidation(ErrorvalidationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorvalidation -->
</testsuite> <!-- Test -->
