<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Praveens-MBP.Home" failures="1" tests="3" name="ErrorValidation" time="10.541" errors="0" timestamp="2023-12-20T07:35:41 GMT">
  <testcase classname="SwagLabs.Tests.ErrorvalidationTest" name="cartPageErrorValidation" time="4.567"/>
  <testcase classname="SwagLabs.Tests.ErrorvalidationTest" name="confirmationMessageValidation" time="3.441"/>
  <testcase classname="SwagLabs.Tests.ErrorvalidationTest" name="loginErrorvalidation" time="2.224">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not_ match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not_ match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at SwagLabs.Tests.ErrorvalidationTest.loginErrorvalidation(ErrorvalidationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorvalidation -->
</testsuite> <!-- ErrorValidation -->
